CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customerPhone VARCHAR(15) NOT NULL,
  checkInDate DATE NOT NULL,
  checkOutDate DATE NOT NULL,
  roomType VARCHAR(10) NOT NULL,
  roomNo VARCHAR(5) NOT NULL,
  meal VARCHAR(10) NOT NULL,
  noOfDays VARCHAR(5) NOT NULL,
  paidTax DECIMAL(10,2) NOT NULL,
  actualTotal DECIMAL(10,2) NOT NULL,
  totalCost DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 